services:
  pasarguard:
    image: pasarguard/panel:v5.4.1
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /var/lib/pasarguard:/var/lib/pasarguard
  proxy:
    image: caddy:2.8.4
    restart: always
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
